const DB="ShowCueDB",VER=4;let db,state={sets:[],current:null,selected:null,library:{audio:[],video:[]}},editing=null,currentAudio=null,master=1,muted=false,objectUrls=[],tvOn=false,settings={padLayout:50,finishMode:"stop",theme:"dark",padSize:"big",defaultColor:"#a991d7",volumeSync:true};
const TARGET_LUFS=-16,$=id=>document.getElementById(id),uid=()=>crypto.randomUUID?.()||Date.now()+"-"+Math.random(),clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),ext=n=>(String(n).split(".").pop()||"").toLowerCase(),esc=x=>String(x??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m])),fmtTime=s=>{s=Number.isFinite(s)?s:0;return `${Math.floor(s/60)}:${String(Math.floor(s%60)).padStart(2,"0")}`};
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,VER);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains("data"))d.createObjectStore("data")};r.onsuccess=()=>{db=r.result;res()};r.onerror=()=>rej(r.error)})}const get=k=>new Promise((res,rej)=>{const r=db.transaction("data").objectStore("data").get(k);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)}),put=(k,v)=>new Promise((res,rej)=>{const r=db.transaction("data","readwrite").objectStore("data").put(v,k);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)});
async function save(){await put("sets",state.sets);await put("library",state.library);await put("settings",settings)}async function boot(){await openDB();state.sets=await get("sets")||[];state.library=await get("library")||{audio:[],video:[]};settings=Object.assign(settings,await get("settings")||{});if(!state.sets.length){state.sets=[{id:uid(),name:"My First Show",pads:Array.from({length:Math.min(settings.padLayout,12)},()=>({id:uid(),name:"",color:settings.defaultColor,mode:"restart"}))}];await save()}state.current=state.sets[0].id;applySettings();render();renderLyrics();renderSetlists();renderVolume();setTimeout(refreshTvUi,0)}
function currentSet(){return state.sets.find(s=>s.id===state.current)}function selectedPad(){const s=currentSet();return s?.pads.find(p=>p.id===state.selected)||s?.pads.find(p=>p.audioBlob||p.audioName)||s?.pads[0]}function applySettings(){$("padLayout").value=settings.padLayout;$('finishMode').value=settings.finishMode;$('displayTheme').value=settings.theme;$('padSize').value=settings.padSize;document.body.classList.toggle("light",settings.theme==="light");document.documentElement.style.setProperty("--padMin",settings.padSize==="small"?"108px":"148px");document.body.classList.toggle("pads-big",settings.padSize!=="small");document.body.classList.toggle("pads-small",settings.padSize==="small")}
function render(){const s=currentSet();if(!s)return;$('setTitle').textContent=s.name;$('padCount').textContent=`${s.pads.length} / 50`;$('cueGrid').innerHTML="";s.pads.slice(0,Number(settings.padLayout)||50).forEach((p,i)=>$('cueGrid').appendChild(makePad(p,i)));if(!s.pads.length){$('cueGrid').innerHTML='<div class="empty" style="grid-column:1/-1">No pads yet.</div>'}}
function makePad(p,i){const el=document.createElement("div");el.className="pad"+(p.id===state.selected?" selected":"");el.style.background=p.color||settings.defaultColor;el.dataset.id=p.id;el.draggable=true;el.innerHTML=`<div><div class="num">${i+1}</div><div class="kind">${p.audioName?'<span class="badge">AUDIO</span>':''}${p.videoName?'<span class="badge">VIDEO</span>':''}${p.tvPhotoName?'<span class="badge">PHOTO</span>':''}</div></div><div><div class="name">${esc(p.name||"Empty Pad")}</div><div class="file">${esc(p.audioName||"Use Edit to add track")}</div><div class="actions"><button class="go" data-play>▶</button><button data-edit>✎</button></div></div>`;
let dragging=false;el.addEventListener("pointerdown",e=>{if(e.target.closest("button"))return;dragging=false;try{el.setPointerCapture(e.pointerId)}catch{}});el.addEventListener("pointermove",e=>{if(!dragging&&e.buttons&&Math.abs(e.movementX)+Math.abs(e.movementY)>3){if(Math.abs(e.movementX)>Math.abs(e.movementY)){dragging=true;dragId=p.id;el.style.opacity=".65";document.body.style.cursor="grabbing"}}});el.addEventListener("pointerup",async e=>{if(dragging){const target=document.elementFromPoint(e.clientX,e.clientY)?.closest(".pad");if(target&&target!==el){const s=currentSet(),a=s.pads.findIndex(x=>x.id===dragId),b=s.pads.findIndex(x=>x.id===target.dataset.id);if(a>=0&&b>=0){const [q]=s.pads.splice(a,1);s.pads.splice(b,0,q);await save()}}dragging=false;dragId=null;el.style.opacity="";document.body.style.cursor="";render()}});["pointercancel","pointerleave"].forEach(ev=>el.addEventListener(ev,()=>{if(ev==="pointercancel"){dragging=false;dragId=null;el.style.opacity="";document.body.style.cursor=""}}));el.addEventListener("dragstart",e=>{dragging=true;dragId=p.id;e.dataTransfer.effectAllowed="move"});el.addEventListener("dragover",e=>e.preventDefault());el.addEventListener("drop",async e=>{e.preventDefault();if(!dragId||dragId===p.id)return;const s=currentSet(),a=s.pads.findIndex(x=>x.id===dragId),b=s.pads.findIndex(x=>x.id===p.id);const [q]=s.pads.splice(a,1);s.pads.splice(b,0,q);await save();dragging=false;dragId=null;render()});el.querySelector("[data-play]").onclick=e=>{e.stopPropagation();selectPad(p);playPad(p,el)};el.querySelector("[data-edit]").onclick=e=>{e.stopPropagation();openPad(p)};el.onclick=e=>{if(!e.target.closest("button")&&!dragging)playPad(p,el)};return el}
let dragId=null;function selectPad(p){state.selected=p.id;renderLyrics();if(tvOn)updateTvOutput(p,true);refreshTvUi();document.querySelectorAll(".pad").forEach(x=>x.classList.toggle("selected",x.dataset.id===p.id))}
function fileToData(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res({name:file.name,type:file.type||"application/octet-stream",data:r.result});r.onerror=()=>rej(r.error);r.readAsDataURL(file)})}async function dataToBlob(x){if(x?.blob)return x.blob;const r=await fetch(x.data);return await r.blob()}
function audioLike(f){return f?.type?.startsWith("audio/")||["mp3","wav","m4a","aac","flac","ogg","oga","opus","aiff","aif","caf","amr","m4b","mpga","webm"].includes(ext(f?.name))}function videoLike(f){return f?.type?.startsWith("video/")||ext(f?.name)==="mp4"}
async function analyse(blob){const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return 0;try{const ac=new AC(),b=await ac.decodeAudioData(await blob.arrayBuffer());let sum=0,n=0;for(let c=0;c<b.numberOfChannels;c++){const d=b.getChannelData(c),step=Math.max(1,Math.floor(d.length/160000));for(let i=0;i<d.length;i+=step){sum+=d[i]*d[i];n++}}const rms=Math.sqrt(sum/Math.max(1,n)),db=20*Math.log10(Math.max(rms,1e-7));await ac.close();return clamp(TARGET_LUFS-(db+3),-12,12)}catch{return 0}}
async function importTracks(files){let added=0;for(const f of [...files])if(audioLike(f)){const x={id:uid(),name:f.name,type:f.type||"application/octet-stream",blob:await blobFromFile(f)};state.library.audio.push(x);added++}await save();renderLibrary();toast(`${added} audio file${added===1?"":"s"} imported.`)}async function importVideos(files){let added=0;for(const f of [...files])if(videoLike(f)){const x={id:uid(),name:f.name,type:f.type||"application/octet-stream",blob:await blobFromFile(f)};state.library.video.push(x);added++}await save();renderLibrary();toast(`${added} video file${added===1?"":"s"} imported.`)}
function openLibrary(type,p){editing=p?.id||null;$('libraryTitle').textContent=type==="audio"?"Choose Audio Track":"Choose Video";$('libraryModal').dataset.type=type;$('libraryModal').dataset.pad=p?.id||"";renderLibrary();$('libraryModal').classList.add("open")}
function renderLibrary(){const type=$('libraryModal').dataset.type||"audio",list=$('libraryList');list.innerHTML="";const arr=state.library[type]||[];if(!arr.length){list.innerHTML='<div class="hint">No imported files yet. Use Menu → Import Track / Import Video.</div>';return}arr.forEach(x=>{const d=document.createElement("div");d.className="libitem";d.innerHTML=`<div><b>${esc(x.name)}</b><br><small>${esc(x.type||"file")}</small></div><button class="btn primary">Use</button>`;d.querySelector("button").onclick=()=>attachLibrary(type,x);list.appendChild(d)})}
async function attachLibrary(type,x){const s=currentSet(),p=s.pads.find(q=>q.id===$('libraryModal').dataset.pad);if(!p){$('libraryModal').classList.remove("open");return}const blob=await dataToBlob(x);if(type==="audio"){p.audioBlob=blob;p.audioName=x.name;p.audioType=x.type;p.gainDb=await analyse(blob);$('libraryModal').dataset.type="video";$('libraryTitle').textContent="Choose Video (optional)";renderLibrary();toast("Audio attached. Analysing BPM and Key…");await applyAudioMeta(p);toast("Audio attached. BPM and Key detected. Choose a video or close.")}else{p.videoBlob=blob;p.videoName=x.name;p.videoType=x.type;$('libraryModal').classList.remove("open");await save();render();if(p.audioBlob)applyAudioMeta(p);toast("Video attached to cue.")}await save();render();}
function openPad(p=null){editing=p?.id||null;$('modalTitle').textContent=p?"Edit Cue":"Add Cue";$('pName').value=p?.name||"New Cue";$('pColor').value=p?.color||settings.defaultColor;$('pMode').value=p?.mode||"restart";$('pLyrics').value=p?.lyrics||"";$('pTrim').value=p?.trimDb||0;$('trimVal').textContent=p?.trimDb||0;$('pAudio').value="";$('pVideo').value="";$('fileInfo').textContent=p?`${p.audioName||"No audio"}${p.videoName?" • "+p.videoName:""}`:"No files selected";$('deletePad').style.display=p?"block":"none";$('padModal').classList.add("open")}
$('pTrim').oninput=e=>$('trimVal').textContent=e.target.value;$('pVideo').onchange=e=>{if([...e.target.files].some(f=>!videoLike(f)))toast("One or more video files are not recognised by the browser.")};
async function savePad(){const s=currentSet(),old=editing?s.pads.find(x=>x.id===editing):null;if(!old&&s.pads.length>=50){toast("Maximum 50 pads per setlist.");return}const base=old||{id:uid(),mode:"restart",trimDb:0};base.name=$('pName').value.trim()||"Cue";base.color=$('pColor').value;base.mode=$('pMode').value;base.lyrics=$('pLyrics').value;base.trimDb=Number($('pTrim').value)||0;const af=[...$('pAudio').files].filter(audioLike),vf=$('pVideo').files[0];if(af.length&&!old){for(const f of af){const b=await blobFromFile(f);s.pads.push({id:uid(),name:f.name.replace(/\.[^.]+$/,""),color:base.color,mode:base.mode,lyrics:base.lyrics,trimDb:base.trimDb,audioBlob:b,audioName:f.name,audioType:f.type,gainDb:await analyse(b)})}}else{if(af[0]){base.audioBlob=await blobFromFile(af[0]);base.audioName=af[0].name;base.audioType=af[0].type;base.gainDb=await analyse(base.audioBlob)}if(vf){base.videoBlob=await blobFromFile(vf);base.videoName=vf.name;base.videoType=vf.type}if(!old)s.pads.push(base)}state.selected=base.id;await save();$('padModal').classList.remove("open");render();renderLyrics();toast("Cue saved.")}
async function blobFromFile(f){const buf=await f.arrayBuffer();return new Blob([buf],{type:f.type||"application/octet-stream"})}
$('savePad').onclick=savePad;$('cancelModal').onclick=()=>$('padModal').classList.remove("open");$('deletePad').onclick=async()=>{if(!editing)return;const s=currentSet();s.pads=s.pads.filter(p=>p.id!==editing);await save();$('padModal').classList.remove("open");render();renderLyrics()};
let tvWin=null;
function tvWindowAlive(){return tvWin&&!tvWin.closed}
function tvOutputHtml(){return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ShowCue TV Output</title><style>html,body{margin:0;width:100%;height:100%;overflow:hidden;background:#000}body{display:flex;align-items:center;justify-content:center}#stage{width:100vw;height:100vh;background:#000;display:flex;align-items:center;justify-content:center}#stage video,#stage img{width:100%;height:100%;object-fit:contain;display:block}#msg{color:#fff;font:22px -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;text-align:center;padding:30px}</style></head><body><div id="stage"><div id="msg">ShowCue TV Output<br><small style="font-size:14px;opacity:.65">Waiting for a cue…</small></div></div><script>let media=null,url=null;function clear(){if(media){try{media.pause()}catch{}media.remove();media=null}if(url){URL.revokeObjectURL(url);url=null}}function show(m){clear();const stage=document.getElementById('stage');media=document.createElement(m.kind==='video'?'video':'img');media.src=url=URL.createObjectURL(m.blob);media.controls=false;media.autoplay=m.kind==='video';media.playsInline=true;stage.innerHTML='';stage.appendChild(media);if(m.kind==='video'){media.loop=false;media.muted=true;media.play().catch(()=>{})}}addEventListener('message',e=>{const m=e.data||{};if(m.cmd==='show'&&m.blob)show(m);if(m.cmd==='clear'){clear();document.getElementById('stage').innerHTML='<div id="msg">Waiting for a cue…</div>'}if(m.cmd==='sync'&&media&&m.time!=null){try{if(Math.abs(media.currentTime-m.time)>.45)media.currentTime=m.time}catch{}}if(m.cmd==='pause'&&media?.pause)media.pause();if(m.cmd==='play'&&media?.play)media.play().catch(()=>{});if(m.cmd==='fullscreen')document.documentElement.requestFullscreen?.().catch(()=>{})});window.opener?.postMessage({cmd:'ready'},'*');</script></body></html>`}
window.addEventListener('message',e=>{if(e.source===tvWin&&e.data?.cmd==='ready')updateTvOutput(selectedPad(),true)});
function openTvOutput(){if(!tvWindowAlive()){tvWin=window.open('about:blank','ShowCueTV','popup=yes,width=1280,height=720');if(!tvWin){toast("The TV Output window was blocked. Allow pop-ups for ShowCue.");return false}tvWin.document.open();tvWin.document.write(tvOutputHtml());tvWin.document.close()}else{try{tvWin.focus()}catch{}}if(selectedPad())updateTvOutput(selectedPad(),false);return true}
function sendTv(msg){if(tvWindowAlive())try{tvWin.postMessage(msg,'*')}catch{}}
function clearTvOutput(){sendTv({cmd:'clear'})}
function updateTvOutput(p,autoplay=true){if(!tvOn||!p){if(!p)clearTvOutput();return}if(p.tvPhotoBlob){sendTv({cmd:'show',kind:'image',blob:p.tvPhotoBlob});return}if(p.videoBlob){sendTv({cmd:'show',kind:'video',blob:p.videoBlob});if(!autoplay)sendTv({cmd:'pause'});return}clearTvOutput()}
function stopAll(){if(currentAudio){try{currentAudio.pause()}catch{}if(currentAudio.ctx)currentAudio.ctx.close().catch(()=>{});currentAudio=null}document.querySelectorAll(".pad.playing").forEach(x=>x.classList.remove("playing"));clearTvOutput();$('nowPlaying').textContent="Ready";$('playIcon').innerHTML='<path d="M8 5v14l11-7L8 5Z"/>';updateSeek()}
function showVideo(p,autoplay=true){updateTvOutput(p,autoplay)}
async function playPad(p,el){
  if(!p)return;
  if(currentAudio?.padId===p.id){
    if(currentAudio.paused){try{await currentAudio.play();if(tvOn&&p.videoBlob){showVideo(p,true)}}catch{toast("Could not resume this audio file.")}}
    else currentAudio.pause();
    return;
  }
  stopAll();
  selectPad(p);
  if(!p.audioBlob){if(tvOn&&(p.tvPhotoBlob||p.videoBlob)){openTvOutput();updateTvOutput(p,true);toast("TV media cue shown.");}else toast("No audio attached. Tap Edit on this pad to add a track.");return}
  let url;
  try{
    url=URL.createObjectURL(p.audioBlob);
    objectUrls.push(url);
    const a=new Audio();
    a.preload="auto";
    a.src=url;
    a.padId=p.id;
    a.baseGain=clamp(Math.pow(10,((p.gainDb||0)+(p.trimDb||0))/20),0,1);
    a.volume=muted?0:clamp(a.baseGain*master,0,1);
    currentAudio=a;
    el?.classList.add("playing");
    $('nowPlaying').textContent=p.name||p.audioName||"Playing";renderLyrics();if(p.audioBlob&&(!p.bpm||!p.key))applyAudioMeta(p).catch(()=>{});
    $('playIcon').innerHTML='<path d="M7 5h4v14H7zM13 5h4v14h-4z"/>';
    a.ontimeupdate=()=>{updateSeek();if(tvOn&&p.videoBlob&&tvWindowAlive())sendTv({cmd:"sync",time:a.currentTime})};
    a.onloadedmetadata=updateSeek;
    a.onended=()=>{
      el?.classList.remove("playing");
      const s=currentSet(),i=s.pads.findIndex(x=>x.id===p.id);
      if(settings.finishMode==="next"&&s.pads[i+1]){const n=s.pads[i+1];const ne=[...document.querySelectorAll('.pad')].find(x=>x.dataset.id===n.id);playPad(n,ne)}
      else{currentAudio=null;renderLyrics();$('playIcon').innerHTML='<path d="M8 5v14l11-7L8 5Z"/>';clearTvOutput()}
    };
    // Start directly from the user gesture. This is the most reliable iOS/Safari path.
    await a.play();
    if(tvOn&&(p.videoBlob||p.tvPhotoBlob))showVideo(p,true);
  }catch(err){
    console.error(err);
    el?.classList.remove("playing");
    currentAudio=null;
    $('playIcon').innerHTML='<path d="M8 5v14l11-7L8 5Z"/>';
    toast("This audio file could not be played on this device/browser.");
  }
}
function updateSeek(){const a=currentAudio;if(!a){$('seek').value=0;$('elapsed').textContent="0:00";$('duration').textContent="0:00";return}const d=a.duration||0;$('seek').max=d||1;$('seek').value=a.currentTime||0;$('elapsed').textContent=fmtTime(a.currentTime);$('duration').textContent=fmtTime(d)}function pVideoForCurrent(){const s=currentSet();const p=s?.pads.find(x=>x.id===currentAudio?.padId);return !!(p?.videoBlob&&tvWindowAlive())}$('seek').oninput=()=>{if(currentAudio){currentAudio.currentTime=Number($('seek').value);if(tvOn&&pVideoForCurrent())sendTv({cmd:"sync",time:currentAudio.currentTime})}};$('playBtn').onclick=()=>{const p=selectedPad();if(!p){toast('Select a cue first.');return}selectPad(p);const idx=currentSet().pads.findIndex(x=>x.id===p.id);const el=[...document.querySelectorAll('.pad')].find(x=>x.dataset.id===p.id)||null;playPad(p,el)};$('stopBtn').onclick=stopAll;$('rewindBtn').onclick=()=>{if(currentAudio){currentAudio.currentTime=0;updateSeek();if(tvOn&&pVideoForCurrent())sendTv({cmd:'sync',time:0})}};$('nextBtn').onclick=()=>{const s=currentSet(),p=selectedPad(),i=s.pads.findIndex(x=>x.id===p?.id);if(s.pads[i+1]){const n=s.pads[i+1],visibleIndex=i+1<Number(settings.padLayout)?i+1:-1;selectPad(n);const el=visibleIndex>=0?[...document.querySelectorAll('.pad')][visibleIndex]:null;el?.scrollIntoView({behavior:'smooth',block:'nearest'});playPad(n,el)}};if($('masterVolume'))$('masterVolume').oninput=e=>setVol(Number(e.target.value)/100);function setVol(v){master=clamp(v,0,1);if($('masterVolume'))$('masterVolume').value=Math.round(master*100);if(currentAudio){currentAudio.volume=muted?0:clamp((currentAudio.baseGain||1)*master,0,1)}renderVolume();setTimeout(refreshTvUi,0)}$('volumeIcon').onclick=()=>{muted=!muted;$('volumeIcon').classList.toggle('muted',muted);$('volumeIcon').style.opacity=muted?.55:1;$('volumeIcon').classList.toggle('muted',muted);$('muteBtn').style.opacity=muted?.55:1;if(currentAudio)currentAudio.volume=muted?0:clamp((currentAudio.baseGain||1)*master,0,1)};$('muteBtn').onclick=()=>{muted=!muted;$('volumeIcon').classList.toggle('muted',muted);$('muteBtn').style.opacity=muted?.55:1;if(currentAudio){currentAudio.volume=muted?0:clamp((currentAudio.baseGain||1)*master,0,1)}};function renderVolume(){const pct=Math.round(master*100);$('volPct').textContent=pct+"%";const heights=[5,7,9,11,13,15,17,19,21,23];$('volBars').innerHTML=heights.map((h,i)=>`<span class="vbar ${i<pct/10?"":"off"}" style="height:${h}px"></span>`).join("")}
function refreshTvUi(){const on=tvOn;$('tvStatus').textContent=on?"ON":"OFF";$('tvPowerBtn').textContent=on?"📺 TV Output: ON":"📺 TV Output: OFF";$('tvBtn').classList.toggle("active",on);$('tvBtn').setAttribute('aria-expanded',$('tvDrop').classList.contains('open')?'true':'false');const p=selectedPad();$('tvNowTitle').textContent=p?.name||"No cue selected";$('tvNowInfo').textContent=on?(p?.tvPhotoBlob?"Static photo active":p?.videoBlob?"Video active":"No photo/video attached to this cue"):"TV Output is OFF."}
$('tvBtn').onclick=e=>{e.stopPropagation();$('tvDrop').classList.toggle('open');refreshTvUi()};
$('tvPowerBtn').onclick=e=>{e.stopPropagation();tvOn=!tvOn;if(tvOn){openTvOutput();updateTvOutput(selectedPad(),true)}else clearTvOutput();refreshTvUi()};
$('tvOutputBtn').onclick=e=>{e.stopPropagation();if(!tvOn)tvOn=true;openTvOutput();updateTvOutput(selectedPad(),true);refreshTvUi();$('tvDrop').classList.remove('open')};
$('tvFullscreenBtn').onclick=e=>{e.stopPropagation();if(!tvOn)tvOn=true;if(openTvOutput()){sendTv({cmd:'fullscreen'});updateTvOutput(selectedPad(),true)}refreshTvUi();$('tvDrop').classList.remove('open')};
$('tvPhotoUploadBtn').onclick=e=>{e.stopPropagation();const p=selectedPad();if(!p){toast("Select a cue pad first.");return}$('tvPhotoFile').click()};
$('tvVideoUploadBtn').onclick=e=>{e.stopPropagation();const p=selectedPad();if(!p){toast("Select a cue pad first.");return}$('tvVideoFile').click()};$('tvHomeBtn').onclick=e=>{e.stopPropagation();$('tvDrop').classList.remove('open');$('tvBtn').classList.remove('active');$('tvBtn').setAttribute('aria-expanded','false');$('view-home').classList.add('active');document.querySelectorAll('.view').forEach(v=>{if(v.id!=='view-home')v.classList.remove('active')});document.querySelectorAll('.navbtn[data-view]').forEach(b=>b.classList.remove('active'));$('homeBtn').classList.add('active');};
$('tvPhotoFile').onchange=async e=>{const f=e.target.files[0];e.target.value='';const p=selectedPad();if(!f||!p)return;if(!f.type.startsWith('image/')){toast("Please choose an image file.");return}p.tvPhotoBlob=await blobFromFile(f);p.tvPhotoName=f.name;p.tvPhotoType=f.type;await save();if(tvOn){openTvOutput();updateTvOutput(p,true)}render();refreshTvUi();toast("Static photo attached to the selected cue.")};
$('tvVideoFile').onchange=async e=>{const f=e.target.files[0];e.target.value='';const p=selectedPad();if(!f||!p)return;if(!videoLike(f)){toast("Please choose a supported video file.");return}p.videoBlob=await blobFromFile(f);p.videoName=f.name;p.videoType=f.type;await save();if(tvOn){openTvOutput();updateTvOutput(p,true)}render();refreshTvUi();toast("Video attached to the selected cue.")};
$('closeVideo').onclick=()=>$('videoModal').classList.remove('open');
function goHome(){showView('home');$('menuDrop').classList.remove('open');$('tvDrop').classList.remove('open');$('tvBtn').classList.remove('active');$('tvBtn').setAttribute('aria-expanded','false');$('homeBtn').classList.add('active')}
$('menuBtn').onclick=e=>{e.stopPropagation();$('menuDrop').classList.toggle('open');$('tvDrop').classList.remove('open')};$('settingsBtn').onclick=e=>{e.stopPropagation();$('menuDrop').classList.remove('open');$('tvDrop').classList.remove('open');showView('settings')};document.addEventListener('click',e=>{if(!e.target.closest('.menuWrap')){$('menuDrop').classList.remove('open');$('tvDrop').classList.remove('open')}});document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));$('setlistHomeBtn').onclick=goHome;$('settingsHomePageBtn').onclick=goHome;$('exitTopBtn').onclick=()=>{stopAll();try{window.open('','_self');window.close()}catch{}setTimeout(()=>{if(!document.hidden)location.replace('about:blank')},120)};$('lyricsHomeBtn').onclick=goHome;$('menuHomeBtn').onclick=e=>{e.stopPropagation();goHome()};function showView(n){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id==='view-'+n));document.querySelectorAll('.navbtn[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===n));}

$('newSet').onclick=()=>{$('newSetName').value='';$('newSetPads').value=12;$('newSetModal').classList.add('open')};$('cancelNewSet').onclick=()=>$('newSetModal').classList.remove('open');$('createSet').onclick=async()=>{const name=$('newSetName').value.trim()||'New Setlist',count=clamp(parseInt($('newSetPads').value)||1,1,50);const s={id:uid(),name,pads:Array.from({length:count},()=>({id:uid(),name:"",color:settings.defaultColor,mode:"restart"}))};state.sets.push(s);state.current=s.id;state.selected=s.pads[0].id;await save();$('newSetModal').classList.remove('open');render();renderSetlists();showView('home')};
function renderSetlists(){const wrap=$('setlistCards');wrap.innerHTML=state.sets.map(s=>`<div class="setting"><h3>${esc(s.name)}</h3><p>${s.pads.length} pads</p><button class="btn primary" data-open="${s.id}">Open</button> <button class="btn" data-rename="${s.id}">Rename</button> <button class="btn danger" data-delete="${s.id}">Delete</button></div>`).join('');wrap.querySelectorAll('[data-open]').forEach(b=>b.onclick=async()=>{stopAll();state.current=b.dataset.open;state.selected=currentSet().pads[0]?.id;await save();render();renderLyrics();showView('home')});wrap.querySelectorAll('[data-rename]').forEach(b=>b.onclick=async()=>{const s=state.sets.find(x=>x.id===b.dataset.rename),n=prompt('New setlist name:',s.name);if(n){s.name=n;await save();render();renderSetlists()}});wrap.querySelectorAll('[data-delete]').forEach(b=>b.onclick=async()=>{if(state.sets.length<2){toast('Keep at least one setlist.');return}if(confirm('Delete this setlist?')){state.sets=state.sets.filter(x=>x.id!==b.dataset.delete);state.current=state.sets[0].id;await save();render();renderSetlists();renderLyrics()}})}
function renderLyrics(){const s=currentSet(),list=$('lyricsList');if(!s||!list)return;list.innerHTML='';s.pads.forEach((p,i)=>{const b=document.createElement('button');b.className='lyricitem'+(p.id===state.selected?' active':'')+(currentAudio?.padId===p.id?' playing':'');b.innerHTML=`<b>${i+1}. ${esc(p.name||'Empty Pad')}</b><br><span style="font-size:11px">${p.lyrics?'Lyrics / notes':'No lyrics'}</span>`;b.onclick=()=>{selectPad(p);const el=[...document.querySelectorAll('.pad')].find(x=>x.dataset.id===p.id)||null;playPad(p,el)};list.appendChild(b)});const p=selectedPad();$('lyricsTitle').textContent=p?.name||'Select a cue';$('lyricsCue').textContent=p?`Cue ${s.pads.indexOf(p)+1}`:'No cue selected';$('lyricsBody').textContent=p?.lyrics||'No lyrics or notes saved for this cue.';$('lyricsFileName').textContent=p?.lyricsFileName||'';$('lyricsMeta').textContent=`Key ${p?.key||'—'} • BPM ${p?.bpm||'—'}${p?.keyChanges?.length?` • ${p.keyChanges.map(x=>x.to+' @ '+fmtTime(x.time)).join(', ')}`:''}`}
async function estimateBpmAndKey(blob){try{const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return{};const ac=new AC(),buf=await ac.decodeAudioData(await blob.arrayBuffer()),sr=buf.sampleRate,d=buf.getChannelData(0),duration=buf.duration;const step=Math.max(1,Math.floor(sr*.02)),energies=[];for(let i=0;i<d.length;i+=step){let sum=0,end=Math.min(d.length,i+step);for(let j=i;j<end;j++)sum+=d[j]*d[j];energies.push(Math.sqrt(sum/Math.max(1,end-i)))}let peaks=0;for(let i=2;i<energies.length-2;i++){const e=energies[i];if(e>energies[i-1]*1.18&&e>energies[i-2]*1.18&&e>energies[i+1]*1.05&&e>energies[i+2]*1.05)peaks++}const bpm=duration>8?Math.round(clamp(peaks/(duration/60),55,180)):null;const names=['C','C♯','D','E♭','E','F','F♯','G','A♭','A','B♭','B'];function keyFor(startSec,lenSec){const chroma=Array(12).fill(0),a=Math.floor(startSec*sr),z=Math.min(d.length,Math.floor((startSec+lenSec)*sr)),win=Math.min(4096,Math.floor(sr*.1)),hop=Math.max(1024,Math.floor(sr*.2));const bases=[];for(let pc=0;pc<12;pc++){const f=440*Math.pow(2,(pc-9)/12);bases.push(f)}for(let pos=a;pos<z;pos+=hop){const n=Math.min(win,z-pos);for(let pc=0;pc<12;pc++){let re=0,im=0;for(let k=0;k<n;k+=2){const x=d[pos+k],t=k/sr,ph=2*Math.PI*bases[pc]*t;re+=x*Math.cos(ph);im-=x*Math.sin(ph)}chroma[pc]+=Math.hypot(re,im);}}let idx=0;for(let i=1;i<12;i++)if(chroma[i]>chroma[idx])idx=i;return chroma[idx]>0?names[idx]:null}const key=keyFor(0,Math.min(45,duration)),changes=[];if(duration>60){let prev=key;for(let t=45;t<duration;t+=30){const k=keyFor(t,Math.min(30,duration-t));if(k&&prev&&k!==prev){changes.push({time:Math.round(t),from:prev,to:k});prev=k}}}await ac.close();return{bpm,key,keyChanges:changes}}catch{return{}}}
async function applyAudioMeta(p){if(!p?.audioBlob)return;const meta=await estimateBpmAndKey(p.audioBlob);if(meta.bpm)p.bpm=meta.bpm;if(meta.key)p.key=meta.key;if(meta.keyChanges)p.keyChanges=meta.keyChanges;await save();renderLyrics()}
async function importLyricsFile(file){const p=selectedPad();if(!p){toast('Select a cue first.');return}try{let text='';const name=file.name||'';if(file.type==='application/pdf'||ext(name)==='pdf'){if(!window.pdfjsLib){await new Promise((resolve,reject)=>{const sc=document.createElement('script');sc.src='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.4.168/pdf.min.js';sc.onload=resolve;sc.onerror=reject;document.head.appendChild(sc)})}const pdfjs=window.pdfjsLib;if(!pdfjs)throw Error('PDF reader unavailable.');pdfjs.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.4.168/pdf.worker.min.js';const pdf=await pdfjs.getDocument({data:await file.arrayBuffer()}).promise;const pages=[];for(let i=1;i<=pdf.numPages;i++){const page=await pdf.getPage(i),content=await page.getTextContent();pages.push(content.items.map(x=>x.str).join(' '))}text=pages.join('\n\n')}else{text=await file.text();if(ext(name)==='rtf')text=text.replace(/\\[a-z]+\d* ?/gi,'').replace(/[{}]/g,'')}if(!text.trim())throw Error('No readable text found.');p.lyrics=text;p.lyricsFileName=name;await save();renderLyrics();toast('Lyrics imported to the selected cue.')}catch(e){console.error(e);toast('Could not read that lyrics file on this device. TXT/MD/RTF are supported locally; PDF uses the browser PDF reader.')}}
$('importLyricsBtn').onclick=()=>{const p=selectedPad();if(!p){toast('Select a cue first.');return}$('lyricsFile').click()};$('lyricsFile').onchange=async e=>{if(e.target.files[0])await importLyricsFile(e.target.files[0]);e.target.value=''};$('lyricsPlayBtn').onclick=()=>{const p=selectedPad();if(p){const el=[...document.querySelectorAll('.pad')].find(x=>x.dataset.id===p.id)||null;playPad(p,el)}};$('lyricsStopBtn').onclick=stopAll;
$('padLayout').onchange=async e=>{settings.padLayout=Number(e.target.value);const s=currentSet();while(s.pads.length<settings.padLayout&&s.pads.length<50)s.pads.push({id:uid(),name:"",color:settings.defaultColor,mode:"restart"});await save();render()};$('finishMode').onchange=async e=>{settings.finishMode=e.target.value;await save()};$('displayTheme').onchange=async e=>{settings.theme=e.target.value;applySettings();await save()};$('padSize').onchange=async e=>{settings.padSize=e.target.value;applySettings();await save();render()};
$('matchAll').onclick=async()=>{const s=currentSet();$('matchStatus').textContent='Matching tracks…';let n=0;for(const p of s.pads)if(p.audioBlob){p.gainDb=await analyse(p.audioBlob);n++}await save();$('matchStatus').textContent=`Matched ${n} track${n===1?'':'s'} for playback.`;toast('Volume sync complete.')};$('persistBtn').onclick=async()=>{if(navigator.storage?.persist){const ok=await navigator.storage.persist();$('storageStatus').textContent=ok?'Persistent storage requested.':'Browser did not grant persistent storage.'}};$('clearData').onclick=async()=>{if(confirm('Delete all ShowCue setlists and imported media from this browser?')){await put('sets',[]);await put('library',{audio:[],video:[]});location.reload()}};
$('importTrack').onclick=()=>{$('trackFiles').click();$('menuDrop').classList.remove('open')};$('trackFiles').onchange=async e=>{await importTracks(e.target.files);e.target.value=''};$('importVideo').onclick=()=>{$('videoFiles').click();$('menuDrop').classList.remove('open')};$('videoFiles').onchange=async e=>{await importVideos(e.target.files);e.target.value=''};$('closeLibrary').onclick=()=>$('libraryModal').classList.remove('open');$('manualBtn').onclick=()=>{$('manualModal').classList.add('open');$('menuDrop').classList.remove('open')};$('closeManual').onclick=()=>$('manualModal').classList.remove('open');
async function exportPlaylist(){const payload={app:'ShowCue',version:5,exported:new Date().toISOString(),settings,sets:[]};for(const s of state.sets){const ns={...s,pads:[]};for(const p of s.pads){const q={...p};if(p.audioBlob){const f=new File([p.audioBlob],p.audioName||'audio');q.audioData=await fileToData(f);delete q.audioBlob}if(p.videoBlob){const f=new File([p.videoBlob],p.videoName||'video');q.videoData=await fileToData(f);delete q.videoBlob}if(p.tvPhotoBlob){const f=new File([p.tvPhotoBlob],p.tvPhotoName||'photo');q.tvPhotoData=await fileToData(f);delete q.tvPhotoBlob}ns.pads.push(q)}payload.sets.push(ns)}const blob=new Blob([JSON.stringify(payload)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(currentSet()?.name||'ShowCue-Playlist')+'.showcue.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}async function importPlaylist(file){const txt=await file.text(),p=JSON.parse(txt);if(!p?.sets)throw Error('Invalid ShowCue playlist');for(const s of p.sets){for(const q of s.pads||[]){if(q.audioData)q.audioBlob=await dataToBlob(q.audioData);if(q.videoData)q.videoBlob=await dataToBlob(q.videoData);if(q.tvPhotoData)q.tvPhotoBlob=await dataToBlob(q.tvPhotoData);delete q.audioData;delete q.videoData;delete q.tvPhotoData}}state.sets=p.sets;settings=Object.assign(settings,p.settings||{});state.current=state.sets[0]?.id;await save();applySettings();render();renderSetlists();renderLyrics();toast('Playlist loaded.')}
$('exportPlaylist').onclick=()=>{exportPlaylist().catch(e=>toast('Could not export playlist.'));$('menuDrop').classList.remove('open')};$('loadPlaylist').onclick=()=>{$('playlistFile').click();$('menuDrop').classList.remove('open')};$('playlistFile').onchange=async e=>{if(e.target.files[0])try{await importPlaylist(e.target.files[0])}catch(err){toast('Invalid ShowCue playlist file.')}e.target.value=''};
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});boot().catch(e=>{console.error(e);toast('ShowCue could not open its local database.')});
